name: Generate UML Diagrams from PlantUML

on:
  push:
    branches:
      - main
    paths:
      - '**/*.puml'  # Trigger only if PlantUML files are changed
  pull_request:
    paths:
      - '**/*.puml'

jobs:
  generate-uml:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    
    - name: Set up Java (required for PlantUML)
      uses: actions/setup-java@v2
      with:
        java-version
