name: Generate UML Diagrams from PlantUML

on:
  push:
    branches:
      - main
    paths:
      - '**/*.puml'  # Trigger only if PlantUML files are changed
  pull_request:
    paths:
      - '**/*.puml'

jobs:
  generate-uml:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    
    - name: Set up Java (required for PlantUML)
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'zulu'  # Use 'zulu' as the Java distribution
    
    - name: Download PlantUML ZIP archive from SourceForge
      run: |
        # Download the ZIP archive of PlantUML from SourceForge
        echo "Downloading PlantUML ZIP archive from SourceForge..."
        curl -L -o plantuml.zip https://downloads.sourceforge.net/project/plantuml/plantuml.zip
        
        # Check if the ZIP file was downloaded correctly
        if [ ! -f plantuml.zip ]; then
          echo "PlantUML ZIP file not downloaded successfully."
          exit 1
        fi
        
        # Debugging: Show file details
        echo "Downloaded file details:"
        ls -lh plantuml.zip
        file plantuml.zip
        
        # Unzip the downloaded file
        echo "Unzipping PlantUML..."
        unzip -q plantuml.zip
        
        # Verify the .jar file exists
        if [ ! -f plantuml.jar ]; then
          echo "plantuml.jar was not found in the extracted files."
          exit 1
        fi
        
        # Check that the file is a valid JAR file
        if ! file plantuml.jar | grep -q "Java archive"; then
          echo "Downloaded file is not a valid JAR file."
          exit 1
        fi

    - name: Generate UML diagram
      run: |
        java -jar plantuml.jar -tpng use-case.puml  # Change file name as needed
    
    - name: Commit generated UML diagram
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "github-actions@github.com"
        git add use-case.png  # Generated image
        git commit -m "Automated UML diagram generation"
        git push
