name: Generate UML Diagrams from PlantUML

on:
  push:
    branches:
      - main
    paths:
      - '**/*.puml'  # Trigger only if PlantUML files are changed
  pull_request:
    paths:
      - '**/*.puml'

jobs:
  generate-uml:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    
    - name: Set up Java (required for PlantUML)
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'zulu'  # Use 'zulu' as the Java distribution
    
    - name: Download PlantUML jar from GitHub Releases
      run: |
        # Download the PlantUML jar file directly from GitHub Releases
        echo "Downloading PlantUML jar from GitHub Releases..."
        curl -L -o plantuml.jar https://github.com/plantuml/plantuml/releases/download/v1.2025/plantuml-1.2025.jar
        
        # Check if the jar file was downloaded correctly
        if [ ! -f plantuml.jar ]; then
          echo "PlantUML jar file not downloaded successfully."
          exit 1
        fi
        
        # Debugging: Show file details
        echo "Downloaded file details:"
        ls -lh plantuml.jar
        file plantuml.jar
        
        # Check if the file is a valid Java archive (JAR)
        if ! file plantuml.jar | grep -q "Java archive"; then
          echo "Downloaded file is not a valid JAR file."
          exit 1
        fi

    - name: Generate UML diagram
      run: |
        java -jar plantuml.jar -tpng use-case.puml  # Change file name as needed
    
    - name: Commit generated UML diagram
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "github-actions@github.com"
        git add use-case.png  # Generated image
        git commit -m "Automated UML diagram generation"
        git push
